### ISSUE TITLE
Repository improvement

### ISSUE THREAD

**Issue by kettanaito** [fidelman/mokker#2]
## What
Sharing my thoughts and pieces of advice to improve this repository.

## Why
Good repository - good library - good experience.

## How
* `index.js@31` consider the scenario when the port provided to mokker is already in use. Express knows how to fallback to another port, make sure to print out the fallback port in case this happens.
* `routes.js@31` missing space. Right now it would produce: `GETis (a) wrong method`.
* Isn't `request` a save dependency?
* Export library in the supported format. Right now you are using arrow functions, which is a relatively new feature. This may cause your library to fail on old projects. Use bundle tools (webpack, rollup) to bundle the transformed library (see `libraryTarget` option in webpack and ES6 => ES2015).
* Introduce minification to the built bundle. The tools mentioned above will help.
* Do not use version `1.0.0` if it's not yet released (does not have stable API, etc.). A good place to start is `0.1.0`. Make sure to read about [Semantic versioning](http://semver.org/).

**Comment by fidelman** [comment]
resolved

**Comment by fidelman** [comment]
#3
